export const translationKeys = {
  app: {
    projectCreated: "Proyecto creado con ShipOne.",
    nextStep: "## Proximo paso",
    nextStepBullet: "- Define el primer objetivo.",
  },
  health: {
    healthy: "healthy",
    warning: "warning",
    bad: "bad",
  },
  issue: {
    missingNextAction: "Falta el siguiente paso",
    inactiveActive: "Proyecto activo inactivo",
    noReadme: "Falta README",
    noRecentCommits: "Sin commits recientes",
  },
  projectStatus: {
    idea: "Idea",
    active: "Active",
    paused: "Paused",
    finished: "Finished",
  },
  notification: {
    focusEnabled: "Focus mode activado.",
    focusDisabled: "Focus mode desactivado.",
    noPausedProjects: "No hay proyectos pausados.",
    projectNotFound: "No se encontró el proyecto.",
  },
  warning: {
    storageRestoreFailed: "No se pudo recuperar el almacenamiento desde el backup.",
    storageSaveFailed: "No se pudo guardar el almacenamiento.",
    storageRecoveryFailed: "No se pudo recuperar el almacenamiento de ShipOne.",
    gitInitFailed: "No se pudo inicializar Git, pero el proyecto ya existe.",
    gitCommitFailed: "Git se inicializo, pero fallo el commit inicial.",
    githubRepoFailed: "No se pudo crear el repo de GitHub, pero el proyecto local ya existe.",
  },
  tree: {
    metrics: "Metrics",
    focusMode: "Focus mode",
    noNextAction: "Sin next action",
    active: "Active",
    ideas: "Ideas",
    paused: "Paused",
    finished: "Finished",
    total: "Total",
    metricsActive: "Active projects",
    metricsPaused: "Paused projects",
    metricsFinished: "Finished projects",
    finishRatio: "Finish ratio",
    noProjectsYet: "Sin proyectos todavia",
    noActiveProject: "Sin proyecto activo",
    activeWithWarnings: "Active con avisos",
    lastOpened: "Ultima apertura: {0}",
    activeLabel: "activos",
    ideasLabel: "ideas",
    pausedLabel: "pausados",
    finishedLabel: "terminados",
    noProjectsDetail: "Crea un proyecto nuevo o una idea de ejemplo para empezar.",
    noActiveProjectDetail: "Abre un proyecto activo o crea uno nuevo para entrar en focus.",
    groupProjects: "Abre el grupo de proyectos {0}.",
    appearsInGroup: "Aqui apareceran los proyectos de {0}.",
    activeNoNextAction: "Define el siguiente paso para avanzar",
  },
  error: {
    projectNotFound: "No se encontró el proyecto.",
    taskNotFound: "No se encontró la tarea.",
    invalidJson: "JSON invalido en {0}.",
    corruptedProjectList: "Metadata corrupta detectada en lista de proyectos.",
    corruptedProjectSnapshot: "Metadata corrupta detectada en snapshot de proyectos.",
  },
  common: {
    yes: "Si",
    no: "No",
    all: "Todos",
    okay: "Entendido",
    cancel: "Cancelar",
    retry: "Reintentar",
    followWithoutGitHub: "Seguir sin GitHub",
    followWithoutGit: "Seguir sin Git",
    followWithoutCommit: "Seguir sin commit",
    openFolder: "Abrir carpeta",
    openSettings: "Abrir ajustes",
    connectGitHub: "Conectar GitHub",
    createProject: "Crear proyecto",
    createExample: "Crear idea de ejemplo",
    useFolder: "Usar carpeta",
    chooseProject: "Elige un proyecto",
    choosePausedProject: "Elige un proyecto pausado",
    openProject: "Abrir proyecto",
    noProjectsYet: "Todavia no hay proyectos",
    noProjectsYetToStart: "Todavia no hay proyectos. Crea uno para empezar.",
    noProjectsWithFilters: "No hay proyectos con esos filtros. Prueba otra busqueda.",
    noProjectsWithTag: "No hay proyectos con esa etiqueta. Prueba otra etiqueta.",
    chooseNewStatus: "Elige el nuevo estado",
    chooseTask: "Elige una tarea",
    chooseStarter: "Elige un starter",
    chooseOption: "Elige una opcion",
    privateOrPublic: "Privado o público?",
    projectNamePlaceholder: "my-saas-app",
    projectDescriptionPlaceholder: "Proyecto simple para ShipOne",
    nextActionPlaceholder: "Escribe el siguiente paso",
    searchNamePlaceholder: "my-saas-app",
    tagPlaceholder: "frontend",
    typeOrAllPlaceholder: "Elige un tipo o deja todo",
    createLoginPlaceholder: "Crear login",
    mvpPlaceholder: "Login, Dashboard, Deploy",
    finishLoginPlaceholder: "Terminar login",
    askGitLocal: "Quieres inicializar Git en este proyecto?",
    pending: "Pendiente",
    keepActive: "Mantener activo",
    pause: "Pasar a pausado",
    finish: "Marcar terminado",
    whatToDo: "Que hacemos con este proyecto",
    waitingFeedback: "Esperando feedback",
    reviewLogin: "Revisar login",
    blockedByExternalDeps: "Bloqueado por dependencias externas",
    npm: "npm",
    pnpm: "pnpm",
    yarn: "yarn",
  },
  github: {
    notAuthenticated: "GitHub no esta autenticado. Puedes conectarlo ahora o seguir sin GitHub.",
    notAuthenticatedSkipped: "GitHub no esta autenticado. Se omitira la creacion del repo.",
    noCli: "No se encontro GitHub CLI. Instala 'gh' y vuelve a intentarlo.",
    connected: "GitHub ya esta conectado.",
    connectInTerminal: "Abre la terminal para conectar GitHub.",
  },
  status: {
    openFailed: "No se pudo abrir STATUS.md.",
    syncDone: "STATUS.md sincronizado en {0}.",
  },
  projectCreation: {
    askGitHubRepo: "Quieres crear un repo de GitHub?",
    gitLocal: "Git local",
    gitHub: "GitHub",
    projectNamePrompt: "Nombre del proyecto",
    projectDescriptionPrompt: "Descripcion",
    projectFolderExists:
      "Ya existe una carpeta con ese nombre. Prueba otro nombre o elige otra carpeta.",
    sampleIdeaName: "Mi primera idea",
    sampleIdeaDescription: "Describe la idea principal aqui.",
    projectType: "Tipo de proyecto",
    destinationFolder: "Carpeta destino",
    packageManager: "Package manager",
    visibility: "Visibilidad",
    private: "Privado",
    public: "Público",
    blank: "Blank",
    blankDescription: "Starting point for any project.",
    reactVite: "React Vite",
    reactViteDescription: "Frontend app with Vite.",
    nextJs: "Next.js",
    nextJsDescription: "Full app with routing and backend-friendly setup.",
    python: "Python",
    pythonDescription: "Script, bot, automation or CLI tool.",
    nodeApi: "Node API",
    nodeApiDescription: "Node backend or API service.",
  },
  launch: {
    searchProject: "Buscar proyecto",
    filterByType: "Filtrar por tipo",
    filterByTag: "Filtrar por etiqueta",
  },
  onboarding: {
    ready: "ShipOne listo. Ruta base: {0}",
  },
} as const;
