export const translationKeys = {
  app: {
    projectCreated: "Proyecto creado con ShipOne.",
    nextStep: "## Proximo paso",
    nextStepBullet: "- Define el primer objetivo.",
  },
  common: {
    yes: "Si",
    no: "No",
    cancel: "Cancelar",
    retry: "Reintentar",
    followWithoutGitHub: "Seguir sin GitHub",
    followWithoutGit: "Seguir sin Git",
    followWithoutCommit: "Seguir sin commit",
    openFolder: "Abrir carpeta",
    openSettings: "Abrir ajustes",
    connectGitHub: "Conectar GitHub",
    createProject: "Crear proyecto",
    createExample: "Crear idea de ejemplo",
  },
  github: {
    notAuthenticated: "GitHub no esta autenticado. Puedes conectarlo ahora o seguir sin GitHub.",
    notAuthenticatedSkipped: "GitHub no esta autenticado. Se omitira la creacion del repo.",
    noCli: "No se encontro GitHub CLI. Instala 'gh' y vuelve a intentarlo.",
    connected: "GitHub ya esta conectado.",
    connectInTerminal: "Abre la terminal para conectar GitHub.",
  },
  status: {
    openFailed: "No se pudo abrir STATUS.md.",
    syncDone: "STATUS.md sincronizado en {0}.",
  },
  projectCreation: {
    askGitHubRepo: "Quieres crear un repo de GitHub?",
    askGitLocal: "Quieres inicializar Git en este proyecto?",
    gitLocal: "Git local",
    gitHub: "GitHub",
    projectType: "Tipo de proyecto",
    destinationFolder: "Carpeta destino",
    packageManager: "Package manager",
    visibility: "Visibilidad",
    private: "Privado",
    public: "Público",
    blank: "Blank",
    reactVite: "React Vite",
    nextJs: "Next.js",
    python: "Python",
    nodeApi: "Node API",
  },
  launch: {
    noProjectsYet: "Todavia no hay proyectos.",
    noProjectsWithFilters: "No hay proyectos con esos filtros. Prueba otra busqueda.",
    noProjectsWithTag: "No hay proyectos con esa etiqueta. Prueba otra etiqueta.",
    searchProject: "Buscar proyecto",
    filterByType: "Filtrar por tipo",
    filterByTag: "Filtrar por etiqueta",
    chooseProject: "Elige un proyecto",
  },
  onboarding: {
    ready: "ShipOne listo. Ruta base: {0}",
  },
} as const;
